### ISSUE TITLE
LIDAR distance jumps to high values

### ISSUE THREAD

**Issue by kercos** [CreativeRobotics/EnactiveTorchRT2b#1]
When opening the serial plotter we noticed that LIDAR distance signal (blue line) at random time (usually when you move the torch) jumps to very high levels (>>12000) for few data points. See attached screenshots.
This problem does not occur with SONAR input.

![normal](https://user-images.githubusercontent.com/2836492/79704579-0fabd180-82ed-11ea-8c07-3e03c50d8135.png)
![peaks](https://user-images.githubusercontent.com/2836492/79704587-163a4900-82ed-11ea-9795-a4bda421b401.png)

**Comment by CreativeRobotics** [comment]
The LIDAR modules are supposed to send a checksum as part of a data packet, but when tested the checksum was always 0 - this may be a firmware bug in the devices. Without a checksum it is not possible to establish if a packet is valid or not so errors can appear as unusual values. I've attempted to mitigate this by capping the raw data values to within the measurement range of the device. If this still causes problems then some additional filtering may be required. (The files for this and other fixes will be released in the next few days).

I don't currently have a LIDAR module to test updated code with, but I have just ordered one.
