### ISSUE TITLE
Enable printing of debug messages in code

### ISSUE THREAD

**Issue by kercos** [CreativeRobotics/EnactiveTorchRT2b#6]
There seems to be no way to enable the printing of debug messages in the code.
There seems to be the `toggle print` command specific for this purpose, but it doesn't seem to work.
I've noticed that in the last commit (https://github.com/CreativeRobotics/EnactiveTorchRT2b/commit/e379dda2c45291f696694369003d7f4c07e5214f) this command has been replaced by `debug` but this is not being recognized. Is it because we need to update the code in each ESP32 board? If so, how can we do that?

**Comment by CreativeRobotics** [comment]
The debug command in the latest comit worked fine for me, and I get debug messages when it is enabled. I will upload a new commit soon, and double check that all the uploaded files are correct - there could be a discrepancy between what I have on my system and what got uploaded to github...

**Comment by CreativeRobotics** [comment]
I've updated the repo and added more debug support, including saving debug settings to the devices flash memory so they will be loaded the moment the device starts - this allows debug data to be enabled from before the SD card settings file is read.

	- 'debug on' switches general debugging on.
	- 'debug off' switches general debugging off.
	- 'debug' toggles debugging state.
	- 'debug sd on' switches SD card debugging on.
	- 'debug sd off' switches SD card debugging off.
	- 'debug sd' toggles SD card debugging state.
	- 'debug boot on' switches startup debugging on.
	- 'debug boot off' switches startup debugging off.
	- 'debug sd' toggles startup debugging state.
	- 'debug usb on' enables device pausing until a USB serial connection is opened.
	- 'debug usb off' disables device pausing until a USB serial connection is opened.
	- 'debug usb' toggles the state of device pausing until a USB serial connection is opened.
	- 'debug save' saves debugging settings to flash memory for use the next time the device starts.
